[package]
name = "generate-changelog"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"
publish = false

[dependencies]
askama = "0.10.5"
chrono = "0.4.19"
regex = "1.5.4"
serde-hex = "0.1.0"
serde_yaml = "0.8.17"
strum_macros = "0.21.1"

[dependencies.libz-sys]
version = "0.1.3"
features = ["static"]

[dependencies.git2]
version = "0.13.20"
default-features = false

[dependencies.hex]
version = "0.4.3"
features = ["serde"]

[dependencies.semver]
version = "1.0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0.127"
features = ["derive"]
