[book]
language = "en"
src = "src"
title = "Just Programmer's Manual"

[build]
build-dir = "build"

[output.html]
cname = "just.systems"
git-repository-url = "https://github.com/casey/just"
site-url = "/man/en/"

[output.linkcheck]
