[package]
name        = "just"
version     = "0.2.20"
description = "🤖 Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "WTFPL/MIT/Apache-2.0"
homepage    = "https://github.com/casey/just"

[dependencies]
ansi_term     = "^0.9.0"
atty          = "^0.2.1"
brev          = "^0.1.6"
clap          = "^2.0.0"
edit-distance = "^1.0.0"
itertools     = "^0.5.5"
lazy_static   = "^0.2.1"
regex         = "^0.1.77"
tempdir       = "^0.3.5"
unicode-width = "^0.1.3"
