[package]
name = "just"
version = "0.2.16"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
license = "WTFPL/MIT/Apache-2.0"
description = "🤖 Just a command runner"
homepage = "https://github.com/casey/just"

[dependencies]

regex = "^0.1.77"
clap = "^2.0.0"
tempdir = "^0.3.5"
lazy_static = "^0.2.1"
brev = "^0.1.6"
itertools = "^0.5.5"
ansi_term = "^0.9.0"
