[package]
name        = "just"
version     = "0.4.4"
description = "🤖 Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/just"
repository  = "https://github.com/casey/just"
readme      = "crates-io-readme.md"
edition     = "2018"

[features]
default = []
help4help2man = []
summary = []

[dependencies]
ansi_term      = "0.11"
assert_matches = "1"
atty           = "0.2"
clap           = "2.33"
dotenv         = "0.13"
edit-distance  = "2"
env_logger     = "0.6"
itertools      = "0.8"
lazy_static    = "1"
libc           = "0.2"
log            = "0.4.4"
target         = "1"
tempfile       = "3"
unicode-width  = "0.1"

[dependencies.ctrlc]
version  = "3.1.1"
features = ["termination"]

[dev-dependencies]
executable-path   = "1"
pretty_assertions = "0.6"
