[package]
name        = "just"
version     = "0.3.3"
description = "🤖 Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/just"
readme      = "crates-io-readme.md"

[dependencies]
ansi_term      = "0.10"
assert_matches = "1.1.0"
atty           = "0.2.1"
brev           = "0.1.6"
clap           = "2.0.0"
edit-distance  = "2.0.0"
itertools      = "0.7"
lazy_static    = "1.0.0"
libc           = "0.2.21"
regex          = "0.2.2"
tempdir        = "0.3.5"
unicode-width  = "0.1.3"

[dev-dependencies.utilities]
path = "utilities"
