[package]
name        = "just"
version     = "0.4.0"
description = "🤖 Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/just"
readme      = "crates-io-readme.md"
edition     = "2018"

[dependencies]
ansi_term      = "0.11.0"
assert_matches = "1.1.0"
atty           = "0.2.1"
brev           = "0.1.6"
clap           = "2.0.0"
dotenv         = "0.13.0"
edit-distance  = "2.0.0"
env_logger     = "0.6.1"
itertools      = "0.8.0"
lazy_static    = "1.0.0"
libc           = "0.2.21"
log            = "0.4.4"
regex          = "1.0.0"
target         = "1.0.0"
tempdir        = "0.3.5"
unicode-width  = "0.1.3"

[dependencies.ctrlc]
version  = "3.1"
features = ["termination"]

[dev-dependencies]
executable-path = "1.0.0"
