[package]
name        = "just"
version     = "0.5.8"
description = "🤖 Just a command runner"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/just"
repository  = "https://github.com/casey/just"
readme      = "crates-io-readme.md"
edition     = "2018"

[features]
default       = []
help4help2man = []
summary       = []

[dependencies]
ansi_term      = "0.12"
atty           = "0.2"
clap           = "2.33"
derivative     = "1.0.1"
dotenv         = "0.15"
edit-distance  = "2"
env_logger     = "0.7"
lazy_static    = "1"
libc           = "0.2"
log            = "0.4.4"
snafu          = "0.6"
target         = "1"
tempfile       = "3"
unicode-width  = "0.1"

[dependencies.ctrlc]
version  = "3.1.1"
features = ["termination"]

[dev-dependencies]
executable-path   = "1"
pretty_assertions = "0.6"
which             = "3"

# Until github.com/rust-lang/cargo/pull/7333 makes it into stable,
# this version-less dev-dependency will interfere with publishing
# to crates.io. In the meantime, we can publish with nighlty cargo.
[dev-dependencies.test-utilities]
path = "test-utilities"
