edition = "2018"
match_arm_blocks = false
max_width = 100
newline_style = "Unix"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true

# comment_width = 80
# error_on_line_overflow = true
# error_on_unformatted = true
# format_code_in_doc_comments = true
# format_macro_bodies = true
# format_strings = true
# normalize_comments = true
# imports_granularity = "Crate"
# reorder_impl_items = true
# wrap_comments = true

match_block_trailing_comma = true
struct_field_align_threshold = 20
overflow_delimited_expr = true
